trigger:
  branches:
    include:
      - '*'
  tags:
    include:
      - '*'

jobs:
  - job: Check
    condition: |
      and(
        not(startsWith(variables['Build.SourceBranch'], 'refs/tags/')),
        or(
          eq(variables['Build.Reason'], 'PullRequest'),
          eq(variables['Build.SourceBranch'], 'refs/heads/master')
        )
      )
    pool:
      vmImage: 'VS2017-Win2016'
    steps:
      - template: windows-dependencies.yml
        parameters:
          rustup_toolchain: '1.42.0-x86_64-pc-windows-msvc'
      - script: |
          cargo fmt --all -- --check
          make clippy
        displayName: Run unit tests
        env:
          CI: true

  - job: Test
    timeoutInMinutes: 0
    condition: |
      and(
        not(startsWith(variables['Build.SourceBranch'], 'refs/tags/')),
        ne(variables['Build.Reason'], 'PullRequest'),
        or(
          startsWith(variables['Build.SourceBranch'], 'refs/heads/rc/'),
          in(variables['Build.SourceBranch'], 'refs/heads/master', 'refs/heads/develop')
        )
      )
    pool:
      vmImage: 'VS2017-Win2016'
    steps:
      - template: windows-dependencies.yml
        parameters:
          rustup_toolchain: '1.42.0-x86_64-pc-windows-msvc'
      - script: make test
        displayName: Run integration tests
        env:
          CI: true

  - job: Bench
    timeoutInMinutes: 0
    condition: |
      and(
        not(startsWith(variables['Build.SourceBranch'], 'refs/tags/')),
        ne(variables['Build.Reason'], 'PullRequest'),
        or(
          startsWith(variables['Build.SourceBranch'], 'refs/heads/rc/'),
          in(variables['Build.SourceBranch'], 'refs/heads/master', 'refs/heads/develop')
        )
      )
    pool:
      vmImage: 'VS2017-Win2016'
    steps:
      - template: windows-dependencies.yml
        parameters:
          rustup_toolchain: '1.42.0-x86_64-pc-windows-msvc'
      - script: |
          make example
          make bench_p2p
        displayName: Run integration tests
        env:
          CI: true
